homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 52.360691
  longitude: 4.938765
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

#http:
#  api_password: !secret http_password
#  base_url: pieterrees.duckdns.org:8123
#  ssl_certificate: '/etc/letsencrypt/live/pieterrees.duckdns.org/fullchain.pem'
#  ssl_key: '/etc/letsencrypt/live/pieterrees.duckdns.org/privkey.pem'

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

device_tracker:
  - platform: bluetooth_tracker
    track_new_devices: False
  - platform: tado
    username: !secret tado_username
    password: !secret tado_password
    home_id: !secret tado_homeid

camera:
  - platform: foscam
    ip: 192.168.2.10
    username: !secret foscam_username
    password: !secret foscam_password

switch:  
  - platform: command_line
    switches:
      livingroom_light1:
        friendly_name: Staande lamp
        command_on: "/home/homeassistant/.homeassistant/custom-scripts/kaku1-on.sh"
        command_off: "/home/homeassistant/.homeassistant/custom-scripts/kaku1-off.sh" 

  - platform: command_line
    switches:
      livingroom_light2:
        friendly_name: Kleine lamp
        command_on: "/home/homeassistant/.homeassistant/custom-scripts/kaku2-on.sh"
        command_off: "/home/homeassistant/.homeassistant/custom-scripts/kaku2-off.sh"

  - platform: command_line
    switches:
      studyroom_light1:
        friendly_name: Kleine lamp
        command_on: "/home/homeassistant/.homeassistant/custom-scripts/kaku0-on.sh"
        command_off: "/home/homeassistant/.homeassistant/custom-scripts/kaku0-off.sh" 

  - platform: command_line
    switches:
      bedroom_light1:
        friendly_name: Kleine lamp
        command_on: "/home/homeassistant/.homeassistant/custom-scripts/kaku3-on.sh"
        command_off: "/home/homeassistant/.homeassistant/custom-scripts/kaku3-off.sh" 

  - platform: command_line
    switches:
      bedroom_light2:
        friendly_name: Kleine lamp
        command_on: "/home/homeassistant/.homeassistant/custom-scripts/kaku4-on.sh"
        command_off: "/home/homeassistant/.homeassistant/custom-scripts/kaku4-off.sh"
